I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_interacts.rpy", line 731, in script
    $ forceBackToMap()
  File "game/script_interacts.rpy", line 731, in <module>
    $ forceBackToMap()
NameError: name 'forceBackToMap' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_interacts.rpy", line 731, in script
    $ forceBackToMap()
  File "C:\Users\itms2\NotOneDrive\FeedingTheVelociraptors\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\itms2\NotOneDrive\FeedingTheVelociraptors\renpy\python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script_interacts.rpy", line 731, in <module>
    $ forceBackToMap()
NameError: name 'forceBackToMap' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Feeding the Velociraptors 0.1
Mon Mar 14 16:46:57 2022
